# Spring Boot 프로젝트 전체 설정
spring:
  datasource:
    # AWS EC2 인스턴스의 퍼블릭 IP 주소와 생성한 데이터베이스명을 입력합니다.
    url: jdbc:mariadb://15.135.113.196:3306/a5_db?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    # 데이터베이스 접속 계정 정보
    username: a5_admin
    password: 4622
    driver-class-name: org.mariadb.jdbc.Driver

  spring:
    mail:
      host: smtp.gmail.com
      port: 587
      username: vhghen7@gmail.com
      password: yocetvhdnndpcoho
      properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true
              required: true
            connectiontimeout: 5000
            timeout: 5000
            writetimeout: 5000

  jpa:
    hibernate:
      # 엔티티 구조와 DB 테이블을 자동으로 동기화 (개발 환경용)
      ddl-auto: update
    properties:
      hibernate:
        # 실행되는 SQL 쿼리를 콘솔에 포맷팅하여 출력
        show_sql: true
        format_sql: true

server:
  # 애플리케이션 구동 포트 번호
  port: 8080

# --- AI 연동 설정 (추후 실제 발급받은 키로 교체) ---
ai:
  gemini:
    # 제미나이 API 기본 주소 (Gemini 2.5 Flash 모델 기준, 무료버전 사용 중 하루 20회 호출 가능)
    url: https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent
    key: ${GOOGLE_API_KEY}
  chatgpt:
    # 챗지피티 API 기본 주소
    url: "https://api.openai.com/v1/chat/completions"
    key: "YOUR_CHATGPT_API_KEY"
# AI API Mock Mode Switch (true: 가짜 데이터 사용, false: 실제 API 호출)
  api:
    mock: true

#navitime은 Rapid api 무료 버전을 사용하고 있습니다. 추후 b2b 서비스가 될 경우 정식 키로 변경하시면 됩니다.
navitime:
  api:
    key: ${navitime_API_KEY}

# google maps api 키입니다. 현재 이준희의 키로 되어있으며 추후 학교에서 api 키를 발급 받을 경우 변경
google:
  maps:
    key: ${GOOGLE_Maps_API_KEY}

debug: true